require('gallo.dep')
require('gallo.settings')
require('gallo.keymaps')
require('gallo.startup')
require('gallo.statusline')
require('gallo.theme')
require('gallo.tree')
require('gallo.tabline')
require('gallo.finder')
require('gallo.emmet')
require('gallo.impatient')
require('gallo.indentline')
require('gallo.treesitter')
require('gallo.autocmds')
require('gallo.cmp')

-- LSP
require('gallo.lsp')
require('gallo.lsp').setup()
require('gallo.lsp.python-ls')
require('gallo.lsp.js-ts-ls')
require('gallo.lsp.cpp-ls')
require('gallo.lsp.lua-ls')
require('gallo.lsp.cmake-ls')
require('gallo.lsp.css-ls')
require('gallo.lsp.null-ls')
require('gallo.lsp.json-ls')
-- not working
require('gallo.lsp.tailwind-ls')
require('gallo.lsp.rust-ls')
