require('gallo.plugins')
require('gallo.settings')
require('gallo.keymaps')
require('gallo.dashboard')
require('gallo.statusline')
require('gallo.theme')
require('gallo.tree')
require('gallo.tabline')
require('gallo.finder')
require('gallo.emmet')

-- LSP
require('gallo.lsp')
require('gallo.lsp.completion')
require('gallo.lsp.python-ls')
require('gallo.lsp.js-ts-ls')
require('gallo.lsp.cpp-ls')
require('gallo.lsp.lua-ls')
require('gallo.lsp.cmake-ls')
require('gallo.lsp.css-ls')
require('gallo.lsp.null-ls')
-- not working
-- require('gallo.lsp.tailwind-ls')
